USE MASTER 
GO 

IF NOT EXISTS(SELECT 1 FROM SYS.DATABASES WHERE NAME LIKE 'DB_CD') 
BEGIN
	CREATE DATABASE DB_CD
END
GO
--====================================================================
USE DB_CD
GO


-- TABELAS PAI 
IF NOT EXISTS(SELECT 1 FROM SYS.tables WHERE NAME = 'AUTOR') 
BEGIN 
	CREATE TABLE AUTOR 
	(
		CODIGO_AUTOR INT          NOT NULL,
		NOME_AUTOR   VARCHAR(250) NOT NULL

		PRIMARY KEY (CODIGO_AUTOR)
	)
END

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'MUSICA')
BEGIN 
	CREATE TABLE MUSICA
	(
		CODIGO_MUSICA INT          NOT NULL, 
		NOME_MUSICA   VARCHAR(300) NOT NULL, 
		DURACAO       DECIMAL(5,2) NOT NULL

		PRIMARY KEY (CODIGO_MUSICA)
	)
END

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'CD_CATEGORIA')
BEGIN 
	CREATE TABLE CD_CATEGORIA
	(
		CODIGO_CATEGORIA INT          NOT NULL, 
		MENOR_PRECO      DECIMAL(5,2) NOT NULL,
		MAIOR_PRECO      DECIMAL(5,2) NOT NULL

		PRIMARY KEY (CODIGO_CATEGORIA)
	)
END

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'GRAVADORA') 
BEGIN 
	CREATE TABLE GRAVADORA 
	(
		CODIGO_GRAVADORA INT          NOT NULL, 
		NOME_GRAVADORA   VARCHAR(250) NOT NULL, 
		ENDERECO         VARCHAR(400) NOT NULL, 
		TELEFONE         INT          NULL, 
		CONTATO          VARCHAR(200) NULL, 
		URL              VARCHAR(200) NULL

		PRIMARY KEY (CODIGO_GRAVADORA)
	)
END



-- TABELAS FILHAS 

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'CD')
BEGIN 
	CREATE TABLE CD 
	(
		CODIGO_CD        INT           NOT NULL,
		CODIGO_GRAVADORA INT           NULL, 
		CODIGO_CATEGORIA INT           NOT NULL,
		NOME_CD          VARCHAR(250)  NOT NULL, 
		PRECO_VENDA      DECIMAL(5,2)  NOT NULL, 
		DATA_LANCAMENTO  SMALLDATETIME NULL,
		CD_INDICADO      INT           NULL


		PRIMARY KEY (CODIGO_CD), 

		FOREIGN KEY (CODIGO_GRAVADORA) REFERENCES GRAVADORA    (CODIGO_GRAVADORA),
		FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES CD_CATEGORIA (CODIGO_CATEGORIA)
	)
END


IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'MUSICA_AUTOR')
BEGIN
	CREATE TABLE MUSICA_AUTOR
	(
		CODIGO_MUSICA INT NOT NULL,
		CODIGO_AUTOR  INT NOT NULL,

		FOREIGN KEY (CODIGO_MUSICA) REFERENCES MUSICA (CODIGO_MUSICA),
		FOREIGN KEY (CODIGO_AUTOR)  REFERENCES AUTOR  (CODIGO_AUTOR)
	)
END


IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE NAME = 'FAIXA')
BEGIN 
	CREATE TABLE FAIXA 
	(
		NUMERO_FAIXA  INT NOT NULL, 
		CODIGO_CD     INT NOT NULL, 
		CODIGO_MUSICA INT NOT NULL  

		FOREIGN KEY (CODIGO_CD)     REFERENCES CD     (CODIGO_CD), 
		FOREIGN KEY (CODIGO_MUSICA) REFERENCES MUSICA (CODIGO_MUSICA)
	)
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE NAME = 'AUDITORIA')
BEGIN
	CREATE TABLE AUDITORIA 
	(
		 ID_LOG INT NOT NULL IDENTITY
		,USUARIO VARCHAR(40)
		,ACAO    VARCHAR(40) 
		,TABELA VARCHAR(40) 
		,DATA DATETIME 
		,CODIGO_ALTERADO INT
	)
END
GO





