ALTER PROCEDURE PREECHENCE_DB_CD (@TABELA VARCHAR(MAX), @QTD_REGISTROS INT)
AS 
BEGIN

	DECLARE 
		@CONT INT = 0

	--EXEC RETORNA_ULTIMO_REGISTRO @TABELA, @QTD_REGISTROS , @CONT, @QTD_REGISTROS OUT, @CONT OUT


	--- INSERIR NA AUTOR
	--===============================================

	IF(@TABELA = 'AUTOR')
	BEGIN

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			INSERT INTO AUTOR VALUES (@CONT,(SELECT 'AUTOR' + CONVERT(VARCHAR(100), @CONT)))
			SET @CONT = @CONT + 1 
		END
	END
	--===============================================


	--- INSERIR NA MUSICA
	--===============================================

	
	IF(@TABELA = 'MUSICA')
	BEGIN

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			DECLARE 
				@TEMPO_MUSICA INT = dbo.NUMERO_ALEATORIO(60,1000, RAND()), 
				@NOME_MUSICA VARCHAR(MAX) = (SELECT 'MUSICA' + CONVERT(VARCHAR(MAX), @CONT))

			INSERT INTO MUSICA VALUES (@CONT, @NOME_MUSICA, @TEMPO_MUSICA)
			SET @CONT = @CONT + 1 
		END
	END

	IF(@TABELA = 'CD_CATEGORIA')
	BEGIN 

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			DECLARE 
				@MENOR_PRECO INT = dbo.NUMERO_ALEATORIO(10,50,RAND()),
				@MAIOR_PRECO INT = dbo.NUMERO_ALEATORIO(11,100, RAND()) 

				INSERT INTO CD_CATEGORIA VALUES (@CONT, @MENOR_PRECO, @MAIOR_PRECO)

				SET @CONT = @CONT + 1 
		END
	END
	--============= ============= ============= ============= ============= ============= ============= ============= ============= ============= 

	IF(@TABELA = 'GRAVADORA')
	BEGIN

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			DECLARE 
	
				@NOME     VARCHAR(MAX) = (SELECT 'GRAVADORA' + CONVERT(VARCHAR(MAX), @CONT)),
				@ENDERECO VARCHAR(MAX) = (SELECT 'ENDERECO_GRAVADORA' + CONVERT(VARCHAR(MAX), @CONT)),
				@TELEFONE INT          = (SELECT ROUND((( 999999999 - 111111111 - 1) * RAND() + 111111111),0)),
				@CONTATO  VARCHAR(MAX) = (SELECT 'CONTATO_GRAVADORA' + CONVERT(VARCHAR(MAX), @CONT)),
				@URL      VARCHAR(MAX) = (SELECT 'https://www.gravadora' + CONVERT(VARCHAR(MAX), @CONT) + '.com.br')

				INSERT INTO GRAVADORA VALUES (@CONT, @NOME, @ENDERECO, @TELEFONE, @CONTATO, @URL)

				SET @CONT = @CONT + 1 
		END
	END

	-- TABELA CD COM ASSOCIAÇÃO COM A TABELA GRAVADORA

	--============= ============= ============= ============= ============= ============= ============= ============= ============= 


	IF(@TABELA = 'AUTOR')
	BEGIN
		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			DECLARE 
				@NOME_AUTOR VARCHAR(MAX) = (SELECT 'AUTOR' + CONVERT(VARCHAR(MAX), @CONT))

				INSERT INTO AUTOR VALUES (@CONT, @NOME_AUTOR)

				SET @CONT = @CONT + 1 
		END
	END

	--============= ============= ============= ============= ============= ============= ============= ============= 



	IF(@TABELA = 'CD')
	BEGIN 
		DECLARE 
			@REGISTRO_GRAVADORA INT = 0,
			@REGISTRO_CATEGORIA INT = 0,
			@MIN_GRAVADORA INT = 0, 
			@MAX_GRAVADORA INT = 0,

			@MIN_CATEGORIA INT = 0,
			@MAX_CATEGORIA INT = 0,

			@NOME_CD VARCHAR(MAX),
			@PRECO_VENDA INT,
			@DATA_LANCAMENTO VARCHAR(10), @DIA VARCHAR(2), @MES VARCHAR(2), @ANO VARCHAR(4)
	
			SELECT @MIN_GRAVADORA = MIN(CODIGO_GRAVADORA), @MAX_GRAVADORA = MAX(CODIGO_GRAVADORA) FROM GRAVADORA
			SELECT @MIN_CATEGORIA = MIN(CODIGO_CATEGORIA), @MAX_CATEGORIA = MAX(CODIGO_CATEGORIA) FROM CD_CATEGORIA

		WHILE @CONT <= @QTD_REGISTROS
		BEGIN 
	
			SELECT 
				@REGISTRO_GRAVADORA = (SELECT ROUND((( @MAX_GRAVADORA - @MIN_GRAVADORA - 1) * RAND() + @MIN_GRAVADORA),0)), 
				@REGISTRO_CATEGORIA = (SELECT ROUND((( @MAX_CATEGORIA - @MIN_CATEGORIA - 1) * RAND() + @MIN_CATEGORIA),0)),
				@NOME_CD = (SELECT 'CD' + CONVERT(VARCHAR(MAX), @CONT)),
		
				@DIA  = (SELECT [dbo].[NUMERO_ALEATORIO](1,31,RAND())),
				@MES  = (SELECT [dbo].[NUMERO_ALEATORIO](1,12,RAND())),
				@ANO  = (SELECT [dbo].[NUMERO_ALEATORIO](1960,2019,RAND())),
				@DATA_LANCAMENTO = @ANO + DBO.ZERO_ESQUERDA(@MES) + DBO.ZERO_ESQUERDA(@DIA)


			SELECT @PRECO_VENDA = (SELECT ROUND(((MAIOR_PRECO - MENOR_PRECO - 1) * RAND() + MENOR_PRECO),0))
			FROM CD_CATEGORIA 
			WHERE CODIGO_CATEGORIA = @REGISTRO_CATEGORIA
	
			INSERT INTO CD VALUES (@CONT, @REGISTRO_GRAVADORA, @REGISTRO_CATEGORIA, @NOME_CD, @PRECO_VENDA, @DATA_LANCAMENTO,NULL)

			SET @CONT = @CONT + 1 
		END
	END
	--============= ============= ============= ============= ============= ============= ============= ============= ============= ============= ============= 



	IF(@TABELA = 'MUSICA_AUTOR')
	BEGIN

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
			DECLARE 
		
				@MIN_AUTOR  INT,  @MAX_AUTOR  INT, @AUTOR  INT, 
				@MIN_MUSICA INT , @MAX_MUSICA INT, @MUSICA INT
		
				SELECT @MIN_AUTOR  = MIN(CODIGO_AUTOR), @MAX_AUTOR   = MAX(CODIGO_AUTOR)  FROM AUTOR
				SELECT @MIN_MUSICA = MIN(CODIGO_MUSICA), @MAX_MUSICA = MAX(CODIGO_MUSICA) FROM MUSICA	

				SELECT 
					@AUTOR  = DBO.NUMERO_ALEATORIO(@MIN_AUTOR, @MAX_AUTOR, RAND()),
					@MUSICA = DBO.NUMERO_ALEATORIO(@MIN_MUSICA, @MAX_MUSICA, RAND())

		
				INSERT INTO MUSICA_AUTOR VALUES (@MUSICA, @AUTOR)

				SET @CONT = @CONT + 1 
		END
	END


	IF(@TABELA = 'FAIXA')
	BEGIN 

		DECLARE 
			@MIN_CD     INT, @MAX_CD     INT, @CD INT,
			@MIN_MUSICA_FAIXA INT, @MAX_MUSICA_FAIXA INT, @MUSICA_FAIXA INT

			SELECT @MIN_CD = MIN(CODIGO_CD), @MAX_CD = MAX(CODIGO_CD) FROM CD
			SELECT @MIN_MUSICA_FAIXA = MIN(CODIGO_MUSICA), @MAX_MUSICA_FAIXA = MAX(CODIGO_MUSICA) FROM MUSICA
	

			IF (SELECT COUNT(*) AS QTD FROM FAIXA ) > 0
			BEGIN 
				SET @CONT = (SELECT MAX(NUMERO_FAIXA) + 1 FROM FAIXA )
				SET @QTD_REGISTROS = @QTD_REGISTROS + @CONT
			END
		

		WHILE @CONT <= @QTD_REGISTROS 
		BEGIN
				SELECT 
					@CD          = DBO.NUMERO_ALEATORIO(@MIN_CD, @MAX_CD, RAND()),
					@MUSICA_FAIXA = DBO.NUMERO_ALEATORIO(@MIN_MUSICA_FAIXA, @MAX_MUSICA_FAIXA, RAND())

				INSERT INTO FAIXA VALUES (@CONT, @CD, @MUSICA_FAIXA)
		
				SET @CONT = @CONT + 1 
		END
	END

END


