SELECT * FROM sys.tables 

GO
-- INSERIR AUTOR 

CREATE PROC INSERE_AUTOR (@CODIGO_AUTOR INT, @NOME_AUTOR VARCHAR(250)) 
AS 
BEGIN
	INSERT INTO AUTOR VALUES (@CODIGO_AUTOR, @NOME_AUTOR)
END 
GO 

-- ATUALIZAR AUTOR 

CREATE PROC ATUALIZA_AUTOR (@CODIGO_AUTOR INT, @NOME_AUTOR VARCHAR(250) )
AS 
BEGIN
	UPDATE AUTOR 
	SET NOME_AUTOR = @NOME_AUTOR
	WHERE CODIGO_AUTOR = @CODIGO_AUTOR  
END 
GO
-- EXCLUIR AUTOR 

CREATE PROC EXCLUIR_AUTOR (@CODIGO_AUTOR INT)
AS 
BEGIN
	DELETE FROM AUTOR WHERE CODIGO_AUTOR = @CODIGO_AUTOR 
END
GO

-- INSERIR CD_CATEGORIA

CREATE PROC INSERIR_CD_CATEGORIA (@CODIGO_CATEGORIA INT, @MENOR_PRECO DECIMAL(5,2), @MAIOR_PRECO DECIMAL(5,2))
AS 
BEGIN
	INSERT INTO CD_CATEGORIA VALUES (@CODIGO_CATEGORIA, @MENOR_PRECO, @MAIOR_PRECO) 
END
GO 

-- ATUALIZAR CD_CATEGORIA 

CREATE PROC ATUALIZA_CD_CATEGORIA(@CODIGO_CATEGORIA INT, @MENOR_PRECO DECIMAL(5,2), @MAIOR_PRECO DECIMAL(5,2))
AS 
BEGIN
	UPDATE CD_CATEGORIA 
	SET 
		MENOR_PRECO = @MENOR_PRECO,
		MAIOR_PRECO = @MAIOR_PRECO 
	WHERE CODIGO_CATEGORIA = @CODIGO_CATEGORIA  
END 
GO

-- EXCLUIR CD_CATEGORIA 
CREATE PROC EXCLUIR_CD_CATEGORIA (@CODIGO_CATEGORIA INT)
AS 
BEGIN
	DELETE FROM CD_CATEGORIA WHERE CODIGO_CATEGORIA = @CODIGO_CATEGORIA 
END 
GO

-- INSERIR GRAVADORA 

CREATE PROC INSERIR_GRAVADORA (@CODIGO_GRAVADORA INT, @NOME_GRAVADORA VARCHAR(250), @ENDERECO VARCHAR(400), @TELEFONE INT, @CONTATO VARCHAR(200), @URL VARCHAR(200) )
AS 
BEGIN
	
	INSERT INTO GRAVADORA VALUES (@CODIGO_GRAVADORA, @NOME_GRAVADORA, @ENDERECO, @TELEFONE, @CONTATO, @URL)
	 
END 
GO 

-- ATUALIZAR GRAVADOR 

CREATE PROC ATUALIZA_GRAVADORA (@CODIGO_GRAVADORA INT, @NOME_GRAVADORA VARCHAR(250), @ENDERECO VARCHAR(400), @TELEFONE INT, @CONTATO VARCHAR(200), @URL VARCHAR(200))
AS 
BEGIN 
	UPDATE GRAVADORA
	SET 
		NOME_GRAVADORA = @NOME_GRAVADORA, 
		ENDERECO = @ENDERECO,
		TELEFONE = @TELEFONE, 
		CONTATO  = @CONTATO, 
		URL = @URL 
	WHERE CODIGO_GRAVADORA = @CODIGO_GRAVADORA 
END 
GO 
-- EXCLURI GRAVADOR 

CREATE PROC EXCLUI_GRAVADORA (@CODIGO_GRAVADORA INT)
AS 
BEGIN 
	DELETE FROM GRAVADORA WHERE CODIGO_GRAVADORA = @CODIGO_GRAVADORA 
END
GO 
 
-- INSERIR CD 

CREATE PROC INSERE_CD (@CODIGO_CD INT, @CODIGO_GRAVADORA INT, @CODIGO_CATEGORIA INT, @NOME_CD VARCHAR(250), @PRECO_VENDA DECIMAL(5,2), @DATA_LANCAMENTO SMALLDATETIME, @CD_INDICADO INT)
AS 
BEGIN
	INSERT INTO CD VALUES (@CODIGO_CD, @CODIGO_GRAVADORA, @CODIGO_CATEGORIA, @NOME_CD, @PRECO_VENDA, @DATA_LANCAMENTO, @CD_INDICADO) 
END
GO 
-- ATUALIZAR CD 

CREATE PROC ATUAIZAR_CD (@CODIGO_CD INT, @CODIGO_GRAVADORA INT, @CODIGO_CATEGORIA INT, @NOME_CD VARCHAR(250), @PRECO_VENDA DECIMAL(5,2), @DATA_LANCAMENTO SMALLDATETIME, @CD_INDICADO INT)
AS 
BEGIN
	 UPDATE CD 
	 SET CODIGO_GRAVADORA = @CODIGO_GRAVADORA, CODIGO_CATEGORIA = @CODIGO_CATEGORIA, NOME_CD = @NOME_CD, PRECO_VENDA = @PRECO_VENDA, DATA_LANCAMENTO = @DATA_LANCAMENTO, CD_INDICADO = @CD_INDICADO
	 WHERE CODIGO_CD = @CODIGO_CD   
END 

GO 

-- EXCLUIR CD 

CREATE PROC EXCLUIR_CD (@CODIGO_CD INT)
AS 
BEGIN
	DELETE FROM CD WHERE CODIGO_CD = @CODIGO_CD  
END 


GO 
-- INSERIR MUSICA_AUTOR 

CREATE PROC INSERIR_MUSICA_AUTOR (@CODIGO_MUSICA INT, @CODIGO_AUTOR INT)
AS 
BEGIN 
	INSERT INTO MUSICA_AUTOR VALUES (@CODIGO_MUSICA, @CODIGO_AUTOR)
END
GO 
 

-- INSERIR FAIXA 

CREATE PROC INSERE_FAIXA (@NUMERO_FAIXA INT, @CODIGO_CD INT, @CODIGO_MUSICA INT)
AS 
BEGIN 
	INSERT INTO FAIXA VALUES (@NUMERO_FAIXA, @CODIGO_CD, @CODIGO_MUSICA)
END
GO

-- ATUALIZAR FAIXA 

CREATE PROC ATUALIZA_FAIXA (@NUMERO_FAIXA INT, @CODIGO_CD INT, @CODIGO_MUSICA INT)
AS 
BEGIN
	UPDATE FAIXA 
	SET   CODIGO_MUSICA = @CODIGO_MUSICA, CODIGO_CD = @CODIGO_CD
	WHERE NUMERO_FAIXA = @NUMERO_FAIXA AND CODIGO_CD = @CODIGO_CD 
END 
GO 

-- EXCLUIR FAIXA


CREATE PROC EXCLUI_FAIXA (@NUMERO_FAIXA INT, @CODIGO_CD INT, @CODIGO_MUSICA INT)
AS 
BEGIN 
	DELETE FROM FAIXA WHERE NUMERO_FAIXA = @NUMERO_FAIXA AND CODIGO_CD = @CODIGO_CD AND CODIGO_MUSICA = @CODIGO_MUSICA
END 
GO 
