USE DB_CD
GO 

-- =====================
-- PROCEDURE DE SAUDACAO
-- ======================

CREATE PROCEDURE SP_SAUDACAO 
AS 
DECLARE 
	 @MENSAGEM VARCHAR(25)

SET @MENSAGEM = 'HELLO WORLD'

PRINT @MENSAGEM
GO


EXEC SP_SAUDACAO
GO

-- ==================
-- PROCEDURE DE SOMA
-- ==================

CREATE PROCEDURE SP_SOMA (@NUM1 INT, @NUM2 INT, @RESULTADO INT OUTPUT)
AS
SET @RESULTADO = @NUM1 + @NUM2

GO

-- ===========================
-- TESTE DA PROCEDURE DE SOMA 
-- ===========================
DECLARE 
	@RESULTADO INT
EXEC SP_SOMA 20, 20, @RESULTADO OUTPUT 

SELECT @RESULTADO AS RESULTADO 
GO


-- =======================
-- PROCEDURE DE SUBTRAÇÃO
-- =======================

CREATE PROCEDURE SP_SUBTRACAO (@NUM1 INT, @NUM2 INT, @RESULTADO INT OUT)
AS 

	SET @RESULTADO = @NUM1 - @NUM2
GO

-- ==========================
-- PROCEDURE DE MULTIPLICAÇÃO
-- ===========================

CREATE PROCEDURE SP_MULTIPLICACAO (@NUM1 INT, @NUM2 INT, @RESULTADO INT OUT) 
AS 
	SET @RESULTADO = @NUM1 * @NUM2 
GO

-- =====================
-- PROCEDURE DE DIVISAO 
-- =====================

CREATE PROCEDURE SP_DIVISAO (@NUM1 INT, @NUM2 INT, @RESULTADO INT OUT) 
AS 
	SET @RESULTADO = @NUM1 / @NUM2
GO


-- =====================
-- PROCEDURE DE CALCULO
-- =====================

CREATE PROCEDURE SP_CALCULA (@NUM1 INT, @NUM2 INT, @OPERACAO CHAR(1), @RESULTADO_FINAL INT OUT)
AS 
	DECLARE @RESULTADO INT 

	IF(@OPERACAO = '+')
	BEGIN
		EXEC SP_SOMA @NUM1, @NUM2, @RESULTADO OUT  
	END

	ELSE IF(@OPERACAO = '-')
	BEGIN 
		EXEC SP_SUBTRACAO @NUM1, @NUM2, @RESULTADO OUT
	END 

	ELSE IF(@OPERACAO = '*')
	BEGIN 
		EXEC SP_MULTIPLICACAO @NUM1, @NUM2, @RESULTADO OUT
	END

	ELSE IF(@OPERACAO = '/') 
	BEGIN
		EXEC SP_DIVISAO @NUM1, @NUM2, @RESULTADO OUT 
	END 

	SET @RESULTADO_FINAL = @RESULTADO
GO

DECLARE	
	@SAIDA INT 

EXEC SP_CALCULA 10, 1231, '-', @SAIDA OUT 
SELECT @SAIDA AS RESULTADO 



-- ================================
-- PROCEDURE DE INSERÇÃO DE MÚSICA
-- ================================

USE DB_CD
GO

CREATE PROCEDURE SP_INSERE_MUSICA (@CODIGO_MUSICA INT, @NOME_MUSICA VARCHAR(100), @DURACAO DECIMAL(3,2))
AS 

	INSERT INTO MUSICA VALUES (@CODIGO_MUSICA, @NOME_MUSICA, @DURACAO)

GO 


-- ===========================
-- PROCEDURE UPDATE DA MÚSICA 
-- ===========================

CREATE PROCEDURE SP_ATUALIZA_MUSICA (@CODIGO_MUSICA INT, @NOME_MUSICA VARCHAR(100))
AS 

	UPDATE MUSICA 
	SET 
		NOME_MUSICA = @NOME_MUSICA
	WHERE CODIGO_MUSICA = @CODIGO_MUSICA
GO


-- =========================
-- PROCEDURE EXCLUIR MUSICA
-- =========================

CREATE PROCEDURE SP_EXCLUIR_MUSICA (@CODIGO_MUSICA INT)
AS 

	DELETE 
	FROM MUSICA
	WHERE CODIGO_MUSICA = @CODIGO_MUSICA
GO 

-- ============================
-- PROCEDURE BUSCA MAIOR PRECO
-- ============================

CREATE PROCEDURE SP_BUSCA_MAIOR_PRECO AS 

	SELECT 
		MAX(PRECO_VENDA)
	FROM CD 
GO


-- ======================
-- PROCEDURE BUSCA VALOR
-- ======================

CREATE PROCEDURE SP_BUSCA_VALOR (@PRECO_VENDA DECIMAL(6,2))
AS

	SELECT 
		 CODIGO_CD
		,CODIGO_GRAVADORA
		,CODIGO_CATEGORIA
		,NOME_CD
		,PRECO_VENDA
		,DATA_LANCAMENTO
		,CD_INDICADO
	FROM CD 
	WHERE PRECO_VENDA > @PRECO_VENDA
	
GO