/*
	FUNÇÕES
*/

USE DB_CD
-- AVG PARA MEDIA DA COLUNA SELECIONADA
SELECT AVG(PRECO_VENDA) AS MEDIA
FROM CD

-- MIN() PARA O MINIMO DE UM CONJUNTO DE DADOS
SELECT MIN(DURACAO) AS MINIMO_DURACAO
FROM MUSICA

-- MAX() PARA O MÁXIMO DE UM CONJUTO DE DADOS
SELECT MAX(MAIOR_PRECO) AS MAIOR_PRECO
FROM CD_CATEGORIA

-- CONT() PARA CONTAGEM DE LINHAS (TUPLAS) DE UM CONJUNTO DE DADOS
SELECT COUNT(*) AS CONT_MUS_AUT
FROM MUSICA_AUTOR

-- SUM() PARA A SOMA DE VALORES DE UM CONJUNTO DE DADOS
SELECT SUM(DURACAO) AS SOMA_DURACAO
FROM MUSICA

-- VAR() A VARIANCIA DE UM CONJUNTO DE DADOS 
SELECT VAR(PRECO_VENDA) AS VARIANCIA_PRECO_CD
FROM CD

-- STDEV() PARA O DESVIO PADRAO DE UM CONJUNTO DE DADOS
SELECT STDEV(PRECO_VENDA) AS DESVIO_PADRAO_CD
FROM CD


/*- LEFT() PEGA O VALOR QUE FOI DETERMINADO NO SEGUNDO PARÂMETRO DA ESQUERDA PARA A DIREITA
	SINTAXE 
	LEFT(STRING, QUANTIDADE DE CARACTERES QUE DEVEM RETORNAR)

	EXEMPLO
	
	DECLARE @NOME VARCHAR(100) = 'MARIA'

	SELECT LEFT(@NOME,3) AS APENAS_MAR
	

*/
SELECT * 
FROM GRAVADORA
WHERE LEFT(ENDERECO,3) = 'ROD' OR LEFT(ENDERECO,2) = 'AV'


-- UPPER() DEIXA AS LETRAS MAIUSCULAS

SELECT UPPER(NOME_MUSICA)
FROM MUSICA

-- LOWER() DEIXA AS LETRAS MINUSCULAS
SELECT LOWER(URL)
FROM GRAVADORA

-- LEN() RETORNA UM INTEIRO DA QUANTIDADE DE CARACTERES DE UMA STRING OU PALAVRA

SELECT LEN(NOME_MUSICA)
FROM MUSICA
WHERE LEN(NOME_MUSICA) < 10 

-- ASCII RETORNA O CÓDIGO ASCII DA PRIMEIRA LETRA DE UMA PALAVRA
SELECT ASCII('FATEC')
SELECT ASCII('fatec')
SELECT ASCII('f')
SELECT ASCII('F')

-- FUNCIONA IGUALMENTE AO LEFT, PORÉM LENDO DA DIREITA PARA A ESQUERDA.
SELECT RIGHT(NOME_AUTOR,5)
FROM AUTOR 

SELECT LEFT(ENDERECO,3)
FROM GRAVADORA

-- LOCALIZA OS CARACTERES DE UMA STRING, PASSANDO COMO PARÂMETRO O INICIO DA BUSCA E A QUANTIDADE DE CARACTERES 

SELECT SUBSTRING(NOME_MUSICA, 3,4), NOME_MUSICA
FROM MUSICA

DECLARE @NAS DATETIME = '19980505'

--SELECT 
--DATEDIFF(YEAR,@NAS,GETDATE()) AS ANO, 
--DATEDIFF(MONTH, MONTH(@NAS),MONTH(GETDATE())) AS MESES, 
--DATEDIFF(DAY, DAY(@NAS), DAY(GETDATE())) AS DIAS



SELECT 
DATEDIFF(YEAR, @NAS,GETDATE()) AS ANO, 
DATEDIFF(MONTH, @NAS,GETDATE()) AS MESES, 
DATEDIFF(DAY, @NAS, GETDATE()) AS DIAS



